global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-instances'
    send_resolved: true