version: '3'

services:
  http-dummy-service:
    container_name: http-dummy
    image: rgjcastrillon/http-dummy-service:0.1.0
    networks:
      - backend

  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "8080:80"
      - "2019:2019"
    networks:
      - backend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - backend
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
      
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana:/var/lib/grafana

  alert-manager:
    container_name: alertmanager
    image: prom/alertmanager
    volumes:
      - "./alertmanager:/config"
    command: --config.file=/config/alertmanager.yml --log.level=debug
    networks:
      - backend
    ports:
      - 9093:9093  
networks:
  backend:
    driver: bridge
